### PR TITLE
Add row and column labels to the game board

### LINKED ISSUE #30: Label rows and columns
Add spreadsheet-style headers on each row and column of the displayed game board.

### PR DESCRIPTION
**Pull request by perlmonger42**
I removed the table border (the CSS rule for `table.banqi-board`) because drawing a box around the board-and-labels looks wrong. That border probably wasn't necessary anyway, because each square is already bordered.

Fixes #30 "Label rows and columns".

### CODE REVIEW

**Comment by perlmonger42** [comment]
Here's how it looks with the labels added:

Screen Shot 2020-05-20 at 8 08 24 AM

**Comment by walrii** [comment]
I like it.  But I'm a bit surprised you used <td> instead of <th> for the headers.

**Comment by perlmonger42** [comment]
You're right, @walrii. I don't think I can do that for the row headers, though. Unless there's a <rh> I hadn't heard of.

**Comment by walrii** [comment]
> You're right, @walrii. I don't think I can do that for the row headers, though. Unless there's a I hadn't heard of.

I believe \<th> can be used anywhere.  I think I've used it at the start of each row before.

**Comment by perlmonger42** [comment]
Somewhere along the way, since I took the screenshot above, the layout changed. Now the dead pieces DIV seems to have disappeared. Inspecting the page shows that it's behind the chat DIV. Looking at the CSS, I can't figure out why this is happening.
Screen Shot 2020-05-21 at 7 40 56 AM

**Comment by arbrown** [comment]
I agree with @walrii - I think `<th>` should be used for row headers as well.

The [documentation](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/th#attr-scope) indicates that you can specify whether the header applies to rows/columns, though I think the default (auto) behavior is sufficient here since it's the first element in a `<tr>`.

**Comment by arbrown** [comment]
As for the missing dead pieces div, I wouldn't be surprised if it was just a poorly thought out hard coded css height.  I've never been strong at css, and I suspect when I initially did this, I just hardcoded stuff like that until it looked right.

I'll take a look later today, but if you want to fix some of the hard coded css stuff while you're in there, feel free to beat me to it.

**Comment by arbrown** [comment]
I checked out the change locally, and the dead pieces dive is still there.  Its height was recently changed to `auto` however, so until any dead pieces show up in there, it doesn't reserve space.  We could set the `min-height` to 2x the piece size (2x45... perhaps?) if you want to show some empty space, but I don't particularly care either way.

I also checked that `<th>` works fine for row headers, so I say switch that and I'll merge this PR.

**Comment by perlmonger42** [comment]
I also changed the styling of headers to be driven by type=th instead of class=header, now that all the headers are th.

**Pull request merged**
